### ISSUE TITLE
Neocomplcache causing Vim slow down

### ISSUE THREAD

**Issue by tolusonaike** [spf13/spf13-vim#275] opened 2013-01-25 18:53 UTC
i am running macvim and spf13-vim 3.0

I noticed slow down in my VIM movement and i have pinned down the culprit to neocomplcache. I noticed this issue hasnt been reported here so maybe it was my setup. I setup a clean vim/spf13-vim install and i am still getting the slow down in performance

**Comment by jakzal** [comment] 2013-01-25 20:43
I'm actually experiencing something similar with macvim.

Autocompletion itself is so slow that it is unusable (necomplcache was suppose to speed it up).

**Comment by jcbwlkr** [comment] 2013-02-02 05:19
I feel like I have had some similar issues but only when I work in some larger files (4k+ lines)

**Comment by jaywilliams** [comment] 2013-02-05 05:28
I'm in the same boat as well. When editing large files, it's painfully slow. I sometimes enable Paste mode (`F12`) to help alleviate the problem.

**Comment by ashleyhindle** [comment] 2013-02-07 11:59
As am I. It's currently unusable, I'm going to have to remove it even though I installed spf13 mostly for the auto completion.

**Comment by Moddus** [comment] 2013-02-11 20:46
Same problem here. I using macvim and in large c-Files is macvim blocked for 1-2 Minutes.

**Comment by jasonmorganson** [comment] 2013-02-13 16:34
The discussion on the group here:
https://groups.google.com/forum/#!topic/spf13-vim-discuss/jq-7LP2PPEg

Points to tips for neocomplcache here:
https://github.com/Shougo/neocomplcache/wiki/neocomplcache-tips%3A

I found it was helpful to switch to only loading autocomplete on TAB. YMMV.

**Comment by jasonmorganson** [comment] 2013-04-13 21:47
I switched to the [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) plugin. It feels faster to me.

In the authors words of the [README](https://github.com/Valloric/YouCompleteMe#readme):

> In essence, YCM obsoletes the following Vim plugins because it has all of their features plus extra:
> - clang_complete
> - AutoComplPop
> - Supertab
> - neocomplcache

**Comment by spf13** [comment] 2013-04-14 00:11
I've been looking into this. Big issue is the install isn't easily
automated and unfortunately requires the vundle installed prior to some
manual steps.

Steve Francia
spf13.com
@spf13

On Apr 13, 2013, at 5:47 PM, Jason Morganson notifications@github.com
wrote:

I switched to the YouCompleteMe
https://github.com/Valloric/YouCompleteMeplugin. It feels faster to
me.

In the authors words of the
READMEhttps://github.com/Valloric/YouCompleteMe#readme
:

In essence, YCM obsoletes the following Vim plugins because it has all of
their features plus extra:
- clang_complete
- AutoComplPop
- Supertab
- neocomplcache
  
  —
  Reply to this email directly or view it on
  GitHubhttps://github.com/spf13/spf13-vim/issues/275#issuecomment-16341516
  .

**Comment by chrisnicola** [comment] 2013-06-08 15:30
Yeah I've switched to YouCompleteMe as well, but I understand why it might not work so well with SPF13. However I've noticed another problem. While I can disable neocomplcache by removing it from my bundle groups, it still runs all the neocomplcache bindings in `.vimrc`. I've added a check to see if the bundle group is there but I'm wondering if that should be by design or not?

**Comment by spf13** [comment] 2013-06-08 16:11
We've recently committed a fix for this. Just update to latest version.

Steve Francia
spf13.com
@spf13

On Jun 8, 2013, at 11:30 AM, Chris Nicola notifications@github.com wrote:

Yeah I've switched to YouCompleteMe as well, but I understand why it might
not work so well with SPF13. However I've noticed another problem. While I
can disable neocomplcache by removing it from my bundle groups, it still
runs all the neocomplcache bindings in .vimrc. I've added a check to see if
the bundle group is there but I'm wondering if that should be by design or
not?

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/275#issuecomment-19150402
.

**Comment by Shougo** [comment] 2013-06-13 09:47
Hi, I'm author of neocomplcache.

> Neocomplcache causing Vim slow down

You can use neocomplete.vim instead of neocomplcache. It is faster than neocomplcache.
But it requires Vim 7.3.885 and if_lua.

**Comment by cureau** [comment] 2014-03-11 00:41
For people who want to use neocomplache, but disable auto complete (i.e., use TAB instead), this will fix your problem.  Add the following to your .vimrc.local:

```
let g:neocomplcache_disable_auto_complete = 1

inoremap <expr><TAB> pumvisible() ? "\<C-n>" : <SID>check_back_space() ? "\<TAB>" : "\<C-x>\<C-u>"
function! s:check_back_space()"{{{
    let col = col('.') - 1
    return !col || getline('.')[col - 1] =~ '\s'
endfunction"}}
```

 https://github.com/Shougo/neocomplcache.vim/wiki/neocomplcache-tips%3A

**Comment by bronzehedwick** [comment] 2014-08-12 14:50
@tolusonaike, has the fixes worked for you? If so please close :)

**Closed as completed** 2014-08-12 16:08 UTC

**Comment by vitalyisaev2** [comment] 2016-04-26 15:49
Fresh spf13 installation. Auto complete in  small `py` and `sls` (SaltStack) files is very slow and seem to perform as CPU-bound.

**Comment by bmeynell** [comment] 2017-03-08 16:23
> Fresh spf13 installation. Auto complete in small py and sls (SaltStack) files is very slow and seem to perform as CPU-bound.

Same here. Autocomplete unbearably slow for large PHP files.

**Comment by bmeynell** [comment] 2017-03-08 16:34
> Same here. Autocomplete unbearably slow for large PHP files.

I just tried setting `:set nocursorline` as per [this thread](https://groups.google.com/forum/#!topic/spf13-vim-discuss/jq-7LP2PPEg) and see a ~~marked~~ slight improvement in typing speed. ~~Good~~ Small step forward.

**Comment by spf13** [comment] 2017-03-08 22:47
Neocomplcache is quite slow as it's implemented entirely in vimscript. Much
faster is neocomplete if you can use that.

**Comment by Shougo** [comment] 2017-03-08 23:07
deoplete is more faster if you can use neovim.

**Comment by bmeynell** [comment] 2017-03-09 16:47
@spf13 - As far as I can tell I'm already using `neocomplete` (I don't see a reference to `Neocompletecache`) in the bundles list, but DO see `neocomplete.vim`):

```
~/.vim/bundle $ ls
auto-pairs           neosnippet           restore_view.vim  vim-addon-mw-utils    vim-css3-syntax           vim-less              vim-signify           vundle
conflict-marker.vim  neosnippet-snippets  rust.vim          vim-airline           vim-cucumber              vim-litecorrect       vim-snippets          webapi-vim
ctrlp-funky          nerdcommenter        salt-vim          vim-airline-themes    vim-cucumber-align-pipes  vim-markdown          vim-surround          wildfire.vim
ctrlp.vim            nerdtree             sessionman.vim    vim-bufferline        vim-easymotion            vim-multiple-cursors  vim-textobj-indent
emmet-vim            PIV                  syntastic         vim-coffee-script     vim-fugitive              vim-nerdtree-tabs     vim-textobj-quote
fonts                pythoncomplete       tabular           vim-coloresque        vim-haml                  vim-over              vim-textobj-sentence
gist-vim             python_match.vim     tagbar            vim-colors            vim-indent-guides         vim-php-namespace     vim-textobj-user
HTML-AutoCloseTag    python-mode          tlib_vim          vim-colorschemes      vim-javascript            vim-preview           vim-toml
matchit.zip          python.vim           undotree          vim-colors-solarized  vim-json                  vim-rails             vim-twig
neocomplete.vim      rainbow              vim-abolish       vim-commentary        vim-jst                   vim-repeat            vim-wordy
```

```
~/.vim/bundle $ grep -ir Neocompletecache *
~/.vim/bundle $
```

Any other suggestions? 💃
