### ISSUE TITLE
Vim hangs for around 15 min when saving some files

### ISSUE THREAD

**Issue by davisein** [spf13/spf13-vim#349] opened 2013-04-17 19:21 UTC
Hi there,

Since updating the last time I'm having problems saving **python** files on vim with spf13. I'm on Ubuntu 12.04 with the vim included. It does not always hangs but I can't see the pattern. Anyway it hangs 95% of the times. It takes 99% of the CPU meanwhile.

I have been tracking the bug and these are the things I tried:
- Disabling python-mode pyflakes check does not improve.
- Openning other files. I don't see the error on .vim files and text files.
- Disabling gutter doesn't improve the situation.

How can I see what takes so much time and cpu or at least what things are executed to be able to debug the error?

**Comment by ghost** [comment] 2013-04-22 07:06
i've had this problem with php files too. i end up having to kill vim. haven't done much debugging yet to figure out what triggers it.

**Comment by johntyree** [comment] 2013-04-24 22:27
If you ctrl+c while it's hanging, what happens? I have a similar problem with C++, although it's pretty rare by comparison.

Also what happens if you `set ft=` before saving?

**Comment by davisein** [comment] 2013-04-25 12:53
In my case, Ctrl+C doesn't do anything.

What value should I give to ft? I'll try that later

**Comment by davisein** [comment] 2013-04-25 15:02
Ok, I have use ft= and vim thought my file wasn't python anymore. I had the same problem.

If it helps, it appeared the + sign of a new line from git and then it says down:
`"filename.py" 82L, 35383C written

I'm using gvim and sending Ctrl+C is not doing anything. It is just staying there.

**Comment by johntyree** [comment] 2013-04-25 15:18
I was interested in whether or not it was related to some kind of python-specific autocmd.

Does it still happen without gitgutter?

**Comment by davisein** [comment] 2013-04-26 16:34
I have tried with `:GitGutterDisable` and the problem persists. Do I need to UnBundle it?

**Comment by davisein** [comment] 2013-04-26 18:25
I tried to UnBundle it and the problem remains. I have the feeling that is slightly less common but probably is just a coincidence...

Any ideas how to find which Bundle might be giving problem here?

**Comment by johntyree** [comment] 2013-04-26 19:55
You can try `:set verbose=9`, then `:w`. It should tell you pretty much
_everything_ Vim is trying to do. The output will probably be massive, but you
can at least see what the last thing is before it hangs. Maybe that will give us
a clue.

**Comment by nddery** [comment] 2013-05-05 19:30
I use to have this problem and added the following function to my bash_profile. Ran it when the problem appeared and it solved it for a while. Not saying this is a solution but it saved my sanity a couple of times.

```
function cleanVIM()
{

  echo "Cleaning ~/.vimbackup/"
  rm -Rf ~/.vimbackup/*
  echo "Cleaning ~/.vimswap/"
  rm -Rf ~/.vimswap/*
  echo "Cleaning ~/.vimviews/"
  rm -Rf ~/.vimviews/*
  echo "Cleaning ~/.vimundo/"
  rm -Rf ~/.vimundo/*
  echo "All done!"

}
```

**Comment by johntyree** [comment] 2013-05-07 18:52
It's bizarre yes. I had this problem today with a python file. Tracing open files for the vim process had it digging all around the working directory, which had other large subdirectories in it. Maybe it's doing some kind of recursive update based on files in `$CWD` ?  I don't know. I haven't used Vim's profiling stuff and I'm not thrilled about learning it.

**Comment by davisein** [comment] 2013-05-08 11:57
I have tracked this problem down. The reason why it didn't work before was because there was two delays.

One of them was rope from python-mode. It was the biggest problem by far. Here is the link to the documentation. My python project is quite big and at some point I had a big .ropeproject. Simple disabling this solved 90% of the problem.

The reason why disable python-mode didn't work was that also gitgutter was giving problems. This showed that 

```
 :GitGutterDisable
```

To do it forever just add this to your `.vimrc.local`

```
 UnBundle 'airblade/vim-gitgutter'
```

For me the bug it's closed. I hope it is useful for other people...

**Comment by spf13** [comment] 2013-05-08 12:30
Wow. Thanks for tracking this down.

Steve Francia
spf13.com
@spf13

On May 8, 2013, at 7:57 AM, David Navarro Estruch notifications@github.com
wrote:

I have tracked this problem down. The reason why it didn't work before was
because there was two delays.

One of them was rope from python-mode. It was the biggest problem by far.
Here is the link to the documentation. My python project is quite big and
at some point I had a big .ropeproject. Simple disabling this solved 90% of
the problem.

The reason why disable python-mode didn't work was that also gitgutter was
giving problems. This showed that

 :GitGutterDisable

To do it forever just add this to your .vimrc.local

 UnBundle 'airblade/vim-gitgutter'

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/349#issuecomment-17600852
.

**Comment by johntyree** [comment] 2013-05-08 18:34
I had this long delay in C++ and well before I discovered git-gutter, which was actually just a week or two ago.  Also someone earlier in thread tried disabling and eventually unbundling it too. Maybe for them Rope was such a problem that they didn't notice the difference it made, but is Rope even active for C++ files?

**Comment by davisein** [comment] 2013-05-08 20:30
As far as I know rope is activated by python-mode only for python. So it
shouldn't be a problem in other languages.

So I guess it shouldn't be that. But you could try the ideas of this
thread. They were really useful to find the troubling modules.

2013/5/8 John Tyree notifications@github.com

> I had this long delay in C++ and well before I discovered git-gutter,
> which was actually just a week or two ago. Also someone earlier in thread
> tried disabling and eventually unbundling it too. Maybe for them Rope was
> such a problem that they didn't notice the difference it made, but is Rope
> even active for C++ files?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spf13/spf13-vim/issues/349#issuecomment-17625036
> .

## 

David Navarro Estruch

**Comment by bronzehedwick** [comment] 2014-08-14 15:49
@davisein, is this problem still occurring?

**Comment by davisein** [comment] 2014-08-14 16:12
After applying both fixes yes. The problem with huge python projects
continue. The problem with gitgutter is less of a problem but I disabled it
for a project with lots of git modules.

You can close out because is nothing inherent about spf13 but with rope
and  gutter hanging vim while operating for long time.

I am currently working with smaller projects that take so much time do it
might depend on your needs.

Congratulation on tracking open issues and helping this project.

Closes #349

**Comment by bronzehedwick** [comment] 2014-08-14 19:01
@davisein, thanks for responding! Did you intend to close the issue? If so, it just printed the text to the comment ;)

**Comment by davisein** [comment] 2014-08-14 19:05
I did indeed xD. Can you close it? I'm not at the computer right now.

Thanks and keep with the good work.

**Comment by bronzehedwick** [comment] 2014-08-14 19:09
I don't actually have the power to close... @johntyree, would you mind doing the honors?

**Comment by ghost** [comment] 2014-08-14 21:55
i will close.

**Closed as completed by ghost** 2014-08-14 21:55 UTC

**Comment by davisein** [comment] 2014-08-16 13:49
Thank you

**Comment by johntyree** [comment] 2014-08-16 18:49
@jrobeson :+1:

**Comment by ghost** [comment] 2014-08-16 23:17
he's alive!

**Comment by bgenchel** [comment] 2019-03-31 21:47
@johntyree 
> You can try `:set verbose=9`, then `:w`. It should tell you pretty much
> _everything_ Vim is trying to do. The output will probably be massive, but you
> can at least see what the last thing is before it hangs. Maybe that will give us
> a clue.

I found this to be so interruptive that I couldn't actually get anything done at all. When I set verbose=9, a buffer opened up at the bottom of my vim screen and it seemed like literally any command or edit I would make to my document would force my cursor / focus down into the bottom buffer where something like 'press Enter to continue' was written. Even when I pressed enter, there was some crazy focus shift / glitching happening. 

Seems like this could be very useful, but perhaps there is some setting I need to activate so that the logging doesn't actively interrupt me from recreating the error?

**Comment by johntyree** [comment] 2019-04-01 22:16
@bgenchel ctrl+c will kill that particular logging event, but as soon as anything else starts happening it will start again.

Don't turn on verbose until you're ready to repro.

**Comment by bgenchel** [comment] 2019-04-02 00:25
@johntyree repro?

**Comment by johntyree** [comment] 2019-04-02 16:52
"reproduce the bug."
