### ISSUE TITLE
Problem with arrow keys mapping in insert mode, apparently linked to OmniComplete

### ISSUE THREAD

**Issue by davidbrewer** [spf13/spf13-vim#567] opened 2014-02-19 19:19 UTC
I very recently started having problems with arrow keys when in insert mode; using them causes the letters A B C or D to get inserted. Disabling OmniComplete by adding the following to my .vimrc.before.local fixes the problem:

```
let g:spf13_no_omni_complete = 1
```

I'm pretty sure this is a recent breakage, as I wasn't having this problem until the last couple of weeks when I updated spf13. I update every few weeks, so I would be surprised if this problem was introduced much earlier than mid-January.

Aside from completely disabling OmniComplete, I can also make the problem go away by commenting out the following two lines in .vimrc (lines 426-427):

```
inoremap <expr> <Esc>      pumvisible() ? "\<C-e>" : "\<Esc>"
inoremap <expr> <CR>       pumvisible() ? "\<C-y>" : "\<CR>"
```

I'm on Ubuntu 12.04 and I'm running vim in tmux, though the problem existed outside of tmux as well. I've got TERM=xterm-256color (when outside tmux) and TERM=screen-256color (when inside tmux).

On a related note, it appears that the option for disabling OmniComplete and the option for noninvasive completion conflict with each other. In my .vimrc.before.local I have:

```
let g:spf13_noninvasive_completion = 1
let g:spf13_no_omni_complete = 1
```

When I start vim I get the following error:

```
Error detected while processing /home/dev/.vimrc:
line  728:
E31: No such mapping
```

If I comment either of those flags the error goes away.

**Comment by rhlobo** [comment] 2014-03-16 22:18
I have the exact same issue. It started as soon as I've updated it.

Just as you've said, that seems to fix the issue:

``` vim
let g:spf13_no_omni_complete = 1
```

**Comment by sgon00** [comment] 2014-04-04 12:21
+1. Me too. 
Lucky me. I found your solution. Works.

**Comment by ccll** [comment] 2014-04-23 13:46
Same here.

**Comment by monological** [comment] 2014-07-10 10:12
I'm having the same issue

**Comment by dthul** [comment] 2014-07-12 21:45
I have the same issue since today's upgrade and disabling omni complete did the trick for me.
Still seems like something that should be fixed.

**Comment by ghost** [comment] 2014-07-13 02:07
i'm having the issue too, but i haven't had time to track down what causes it.

**Comment by ghost** [comment] 2014-08-15 06:12
@davidbrewer : what was the difference when commenting out only the
`inoremap <expr> <CR>       pumvisible() ? "\<C-y>" : "\<CR>"`

vs that and 
`inoremap <expr> <Esc>      pumvisible() ? "\<C-e>" : "\<Esc>"`

**Comment by liqiangvip** [comment] 2014-09-01 07:46
Thank you very much! It works!

**Comment by ghost** [comment] 2015-01-03 11:16
@spf13: do you have any insight here?

**Comment by toejough** [comment] 2015-05-02 18:35
Fixed my problem as well.

I was also having a really annoying problem with the completion prompts taking two, sometimes three escapes to get back to normal mode, which resulted in a lot of extra j/k/l/h/u characters in my code.  After disabling omnicomplete this phenomenon when away, too.  Seems like omnicomplete integration is broken...

**Comment by FiloSpaTeam** [comment] 2015-05-02 20:55
Same here.
Today i click ESC 3/4 times every time just for safety :neckbeard:

**Comment by BretFisher** [comment] 2015-05-03 03:25
:+1: same issue and workaround on new Mac today... old Mac that hasn't been updated on spf13 for a while, but both are using same dotfiles.

**Comment by spf13** [comment] 2015-05-03 03:28
I have no insights, but disabling omnicomplete seems like an awful thing to
give up. I don't experience this on my machines. We need a better solution.

Are all of you editing the same type of files? Same OS? more information
here would be very helpful as it's likely a specific plugin causing it.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by BretFisher** [comment] 2015-05-03 05:54
To recreate:
- New VM in Parallels of Mac 10.10.3 Yosemite (built from recovery partition)
- Start Terminal
- install spf13 `curl http://j.mp/spf13-vim3 -L -o - | sh`
- prompts to install xcode tools. Once finished:
- `vim`
- `i`
- use arrow keys
- Up inserts A on newline above current line, Down inserts B, Right inserts C, Left inserts D
- arrow keys work normally in normal mode

I wondered if was my zsh shell, or maybe iterm, but nope, that's as pure of a test as we can get on Mac. A fresh new OS with nothing installed. I'm happy to test other things.

**Comment by FiloSpaTeam** [comment] 2015-05-03 07:34
Normal in vim, arrow keys are seen like ABCD.
Try with this fix that vim wiki gives:
- [Remote](https://www.google.it/url?q=http://vim.wikia.com/wiki/Fix_arrow_keys_that_display_A_B_C_D_on_remote_shell&sa=U&ei=Fs9FVf3NB4nTaIHKgfAN&ved=0CAsQFjAA&usg=AFQjCNF_QU72ZkJntJSYvW5Fxr7fjL0sPQ)
- [Broken arrows](https://www.google.it/url?q=http://vim.wikia.com/wiki/Fix_arrow_keys_that_display_A_B_C_D_on_remote_shell&sa=U&ei=Fs9FVf3NB4nTaIHKgfAN&ved=0CAsQFjAA&usg=AFQjCNF_QU72ZkJntJSYvW5Fxr7fjL0sPQ)

**Comment by gisphm** [comment] 2015-05-03 08:57
After I comment those 'convenient' mappings (as shown below) in `omnicomplete` part, I find `ESC` and `arrow keys` works as expected.

``` VimL
" Some convenient mappings
inoremap <expr> <Esc>      pumvisible() ? "\<C-e>" : "\<Esc>"
inoremap <expr> <Down>     pumvisible() ? "\<C-n>" : "\<Down>"
inoremap <expr> <Up>       pumvisible() ? "\<C-p>" : "\<Up>"
```

**Comment by BretFisher** [comment] 2015-05-03 17:22
Thanks @FiloSpaTeam, solution 15 under Broken arrows works for me with omnicomplete enabled. Added this to `~/.vimrc.local`

``` vim
imap <ESC>oA <ESC>ki
imap <ESC>oB <ESC>ji
imap <ESC>oC <ESC>li
imap <ESC>oD <ESC>hi
```

**Comment by FiloSpaTeam** [comment] 2015-05-03 17:30
Perfect! :dancer: :+1:

**Comment by novalore** [comment] 2015-05-04 15:35
@BretFisher that solution is working for me also, but I still wonder why the problem appeared after the last update...

**Comment by rafaponieman** [comment] 2015-05-04 19:37
@BretFisher worked for me in the case of arrows, but its not fixing the ESC key... any clues?

In the end, I had to disable omnicomplete, and that did the trick...

**Comment by JulianVolodia** [comment] 2015-05-07 21:43
@gisphm have better solution, don't you think the problem is near .vimrc:728 like @davidbrewer said?

anybody knows when it precisely stop working... ? Which commit? Could you blame it?

Hacks like:

> imap <ESC>oA <ESC>ki
> imap <ESC>oB <ESC>ji
> imap <ESC>oC <ESC>li
> imap <ESC>oD <ESC>hi

is not the best, because `:set nocompatible` should repair that bug...

**Comment by gisphm** [comment] 2015-05-08 06:02
@JulianVolodia I don't think the `omnicomplete` part is to blame. I have been using this distribution for half a year(though I forked one recently). Before some recent commits, this distribution worked well.

As you proposed, I checkout some commits as new branches, just for testing which commit maybe the reason why those keys stop working. I find that after [this commit](https://github.com/spf13/spf13-vim/commit/2d4af5a8e33799f309d6a26c96632562efe303b3), arrow keys act as `compatible`. In [this commit](https://github.com/spf13/spf13-vim/commit/2d4af5a8e33799f309d6a26c96632562efe303b3),  [vim-autoclose](https://github.com/spf13/vim-autoclose) is replaced with [auto-pairs](https://github.com/jiangmiao/auto-pairs), meaning that [vim-autoclose](https://github.com/spf13/vim-autoclose) is deleted from `bundle list`.

Well, I am not good at vim script. I have no idea what has been coded in [auto-pairs](https://github.com/jiangmiao/auto-pairs). So, can anybody look into [auto-pairs](https://github.com/jiangmiao/auto-pairs) and find what is the real reason that those keys are not working as expected?

**Comment by JulianVolodia** [comment] 2015-05-08 15:37
you have auto-pairs in .vim/bundle/auto-pairs/plugin/auto-pairs.sh

After disabling it (move that file elsewhere or change name) it still don`t work (arrows).

**Comment by FiloSpaTeam** [comment] 2015-05-08 15:41
If you want disable auto-pairs move directory auto-pairs in another directory and reload Vim, auto-pairs doesn't act anymore and configuration doesn't load if conditions ;-)

**Comment by JulianVolodia** [comment] 2015-05-08 15:48
> doesn't load if conditions

~~what do you mean? Which confitions?~~ Oh, in hurry I don't get you. Yep, I moved in another location to disable plug-in - but problem still happen.

I still looking for sth which broke spf13 to behave like in compatible mode (ABCD letters). @gisphm mentioned that auto-pairs could be badass... but not.

I ask you (all my dear friends :D) to find out which is regressive commit... to collaborate ;)

**Comment by FiloSpaTeam** [comment] 2015-05-08 15:56
In my fork all works as expected but i changed auto-pairs with this [plugin](https://github.com/Raimondi/delimitMate) (that i think is better too, because handles some particular conditions).

In this beautiful .vimrc, most of configurations are loaded only if the plugin exists ;-)
Like:

> if expand("~/.vimrc.bundles.fork")
>     # do something
> endif

**Comment by JulianVolodia** [comment] 2015-05-08 15:59
@FiloSpaTeam - I got it earlier.

> In my fork all works as expected ...

what exacly work? you disabled that plugin and it works?

**Comment by FiloSpaTeam** [comment] 2015-05-08 16:02
I use Vim (with Konsole) and GVim and i don't have problems with Arrows keys.
I replaced plugin with [this](https://github.com/Raimondi/delimitMate) ;-)

**Comment by gisphm** [comment] 2015-05-08 16:25
@julianduque Replace auto-pairs with vim-autoclose, then the arrow keys perform well.
I am confused about those `convenient` mappings in `omnicomplete` part. They are actually `useless`. So I came up with the idea commenting these mappings.
By the way, I use a keyboard with 61 keys, so I don't use arrow keys when coding with vim. :-)

**Comment by ghost** [comment] 2015-05-08 20:03
@JulianVolodia after many changes in spf13-vim, you must clear out the .vimviews directory. Not sure if for this particular plugin though,

**Comment by raratiru** [comment] 2015-05-09 10:57
The suggested solution:

`let g:spf13_no_omni_complete = 1` to `.vimrc.before.local` worked for me in Gnome Terminal.

However, I cannot use arrows to select an entry from the autocomplete menu.

**Comment by diraol** [comment] 2015-05-10 00:29
Friends, the "auto-pairs" plugin was not added, it was just moved from line 159 to 109 on [this commit](https://github.com/spf13/spf13-vim/commit/2d4af5a8e33799f309d6a26c96632562efe303b3). This commit actually removed the "vim-autoclose" plugin.

I've added **Bundle 'spf13/vim-autoclose'** to my _.vimrc.bundle.local_ and after running Bundle to install the plugins this problem with arrow keys was fixed.

I don't know what on "vim-autoclose" fixes this behaviour, but it works. rs =)

**Comment by damianball** [comment] 2015-05-11 18:22
Hey @diraol, I think you meant _.vimrc.bundles.local_

This is the command I ran after adding **Bundle 'spf13/vim-autoclose** to _~/.vimrc.bundles.local_
`vim +BundleInstall! +BundleClean +q`

The ABCD arrow problem is now fixed for me. Thanks @diraol!

**Comment by xiaozongyang** [comment] 2015-05-13 10:42
@davidbrewer it works, thx a lot!

**Comment by lauramoraes** [comment] 2015-05-14 14:15
For me, the only thing that worked was:
imap <ESC>oA <ESC>ki
imap <ESC>oB <ESC>ji
imap <ESC>oC <ESC>li
imap <ESC>oD <ESC>hi

Disabling omni didn't have any effect.

**Comment by regadas** [comment] 2015-05-15 09:27
Adding back `spf13/vim-autoclose` fixes it, thx @diraol @damianball

**Comment by sitano** [comment] 2015-05-28 10:10
:+1:

**Closed as completed** 2015-11-16 23:01 UTC

**Comment by opz** [comment] 2015-11-18 06:34
`spf13/vim-autoclose` fixes this with the following:

```
if &term[:4] == "xterm" || &term[:5] == 'screen' || &term[:3] == 'rxvt'
      inoremap <silent> <C-[>OC <RIGHT>
endif
```
