### ISSUE TITLE
Syntax Highlighting in ActionScript

### ISSUE THREAD

**Issue by ZhiruiLi** [spf13/spf13-vim#708] opened 2014-12-30 04:44 UTC
Hello, @spf13 . I want to add actionscript and mxml syntax files into your Vim. But after I copy them into vim\vim74\syntax folder, there is nothing happen. Do you know why?

The syntax files is here : http://www.vim.org/scripts/script.php?script_id=3225

**Comment by cprn** [comment] 2014-12-30 14:43
This version of VIM is highly modified and depending on your configuration this way of installing add-ons may not work. You should install a Bundle instead (e.g. [vim-actionscript](https://github.com/jamestomasino/actionscript-vim-bundle) plugin).

**Comment by ZhiruiLi** [comment] 2014-12-31 01:08
@cprn It works ! Thank you very much !  ^_^

**Comment by bronzehedwick** [comment] 2015-01-06 15:44
@irrational-lzr - if the problem is resolved, can you close this issue?

**Closed as completed** 2015-01-07 00:26 UTC
