### ISSUE TITLE
Error processing 'plugin_name' vundle

### ISSUE THREAD

**Issue by alioukahere** [spf13/spf13-vim#932] opened 2016-05-21 10:11 UTC
I created the file _**~/.vimrc.bundles.local**_ and add these bundles : 
`Bundle 'Shougo/unite.vim'`
`Bundle 'Shougo/vimproc.vim'`
`Bundle 'm2mdas/phpcomplete-extended'`
when I run the installation with _**:BundleInstall**_, I get errors **_Error processing 'plugin_name'_** for all three bundle. And I don't understand. Help please !!!

**Comment by alexche8** [comment] 2016-05-24 10:45
Did you try this command from terminal ?  vim +BundleInstall! +BundleClean +q.

**Comment by alioukahere** [comment] 2016-05-26 09:41
Thanks  [alexche8](https://github.com/alexche8) it's work.

**Comment by bronzehedwick** [comment] 2016-05-26 13:09
@Alioukahere if the problem is resolved can you close this issue?

**Closed as completed** 2016-05-27 01:54 UTC
